// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $home from "./routes/home.tsx";
import * as $BlogCategories from "./islands/BlogCategories.tsx";
import * as $BlogPostsCarousel from "./islands/BlogPostsCarousel.tsx";
import * as $CopyCommandButton from "./islands/CopyCommandButton.tsx";
import * as $FeaturesInteractive from "./islands/FeaturesInteractive.tsx";
import * as $GitHubStars from "./islands/GitHubStars.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/home.tsx": $home,
  },
  islands: {
    "./islands/BlogCategories.tsx": $BlogCategories,
    "./islands/BlogPostsCarousel.tsx": $BlogPostsCarousel,
    "./islands/CopyCommandButton.tsx": $CopyCommandButton,
    "./islands/FeaturesInteractive.tsx": $FeaturesInteractive,
    "./islands/GitHubStars.tsx": $GitHubStars,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
