// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/airtable/createRecord.ts";
import * as $$$$$$$$$1 from "./actions/resend/createContact.ts";
import * as $$$$$$$$$2 from "./actions/submitFeatureSuggestion.ts";
import * as $$$$$$$$$3 from "./actions/upvoteFeature.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/nuvemshop.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/getRoadmapFeatures.ts";
import * as $$$1 from "./loaders/listFeatures.ts";
import * as $$$2 from "./loaders/posthogConfig.ts";
import * as $$$3 from "./loaders/sitemap.ts";
import * as $$$$$$10 from "./sections/AgentTavano/Benefits.tsx";
import * as $$$$$$12 from "./sections/AgentTavano/Context.tsx";
import * as $$$$$$11 from "./sections/AgentTavano/CTA.tsx";
import * as $$$$$$13 from "./sections/AgentTavano/Features.tsx";
import * as $$$$$$14 from "./sections/AgentTavano/Hero.tsx";
import * as $$$$$$15 from "./sections/AgentTavano/Showcase.tsx";
import * as $$$$$$0 from "./sections/AIPartnerExclusivity.tsx";
import * as $$$$$$1 from "./sections/AIPartnerFinalCTA.tsx";
import * as $$$$$$2 from "./sections/AIPartnerFooter.tsx";
import * as $$$$$$3 from "./sections/AIPartnerHero.tsx";
import * as $$$$$$4 from "./sections/AIPartnerProcessSteps.tsx";
import * as $$$$$$5 from "./sections/AIPartnerProgramOverview.tsx";
import * as $$$$$$6 from "./sections/AIPartnerSocialProof.tsx";
import * as $$$$$$7 from "./sections/AIPartnerTheShift.tsx";
import * as $$$$$$8 from "./sections/AIPartnerValueProposition.tsx";
import * as $$$$$$9 from "./sections/AIPartnerWhoThisIsFor.tsx";
import * as $$$$$$16 from "./sections/Analytics/PostHog.tsx";
import * as $$$$$$17 from "./sections/ApplicationForm.tsx";
import * as $$$$$$18 from "./sections/ApplicationProcess.tsx";
import * as $$$$$$19 from "./sections/AutonomyControl.tsx";
import * as $$$$$$20 from "./sections/BackboneSection.tsx";
import * as $$$$$$21 from "./sections/BentoFeatures.tsx";
import * as $$$$$$22 from "./sections/BlackFridayCountdown.tsx";
import * as $$$$$$23 from "./sections/BlackFridayFeatures.tsx";
import * as $$$$$$24 from "./sections/BlackFridayHero.tsx";
import * as $$$$$$25 from "./sections/BlogCategories.tsx";
import * as $$$$$$26 from "./sections/BlogFilteredPosts.tsx";
import * as $$$$$$27 from "./sections/BlogPost.tsx";
import * as $$$$$$28 from "./sections/BlogPosts.tsx";
import * as $$$$$$29 from "./sections/BlogPostsCarousel.tsx";
import * as $$$$$$30 from "./sections/ChallengeHero.tsx";
import * as $$$$$$31 from "./sections/CommunicationOSFeatures.tsx";
import * as $$$$$$32 from "./sections/CommunicationOSHero.tsx";
import * as $$$$$$33 from "./sections/CommunicationOSJourney.tsx";
import * as $$$$$$34 from "./sections/CommunicationOSProblem.tsx";
import * as $$$$$$35 from "./sections/CommunicationOSSolution.tsx";
import * as $$$$$$36 from "./sections/ComparisonTable.tsx";
import * as $$$$$$37 from "./sections/ConnectionsGrid.tsx";
import * as $$$$$$38 from "./sections/CustomerLogos.tsx";
import * as $$$$$$39 from "./sections/DecoSitesHero.tsx";
import * as $$$$$$40 from "./sections/Document.tsx";
import * as $$$$$$41 from "./sections/EnterpriseComparison.tsx";
import * as $$$$$$42 from "./sections/EnterpriseGovernance.tsx";
import * as $$$$$$43 from "./sections/EnterpriseHero.tsx";
import * as $$$$$$44 from "./sections/EnterprisePainPoints.tsx";
import * as $$$$$$45 from "./sections/EnterpriseStandards.tsx";
import * as $$$$$$46 from "./sections/EnterpriseValueProp.tsx";
import * as $$$$$$47 from "./sections/ExplainerSection.tsx";
import * as $$$$$$48 from "./sections/FAQ.tsx";
import * as $$$$$$49 from "./sections/Features.tsx";
import * as $$$$$$50 from "./sections/FinalCTA.tsx";
import * as $$$$$$51 from "./sections/FinalCTACMS.tsx";
import * as $$$$$$52 from "./sections/FinalCTAMCPMesh.tsx";
import * as $$$$$$53 from "./sections/FinalCTASimple.tsx";
import * as $$$$$$54 from "./sections/FindPartnerHero.tsx";
import * as $$$$$$55 from "./sections/Footer.tsx";
import * as $$$$$$56 from "./sections/FormNewsletter.tsx";
import * as $$$$$$57 from "./sections/FoundationFeatures.tsx";
import * as $$$$$$58 from "./sections/GoogleAbout.tsx";
import * as $$$$$$59 from "./sections/HackathonHero.tsx";
import * as $$$$$$60 from "./sections/Header.tsx";
import * as $$$$$$61 from "./sections/Hero.tsx";
import * as $$$$$$62 from "./sections/HeroAIPlatform.tsx";
import * as $$$$$$63 from "./sections/HeroCMS.tsx";
import * as $$$$$$64 from "./sections/HeroInteractive.tsx";
import * as $$$$$$65 from "./sections/HeroMCPMesh.tsx";
import * as $$$$$$66 from "./sections/HeroSection.tsx";
import * as $$$$$$67 from "./sections/HeroSecureEndpoint.tsx";
import * as $$$$$$68 from "./sections/ImageShowcase.tsx";
import * as $$$$$$69 from "./sections/ItWorks.tsx";
import * as $$$$$$70 from "./sections/LatestBlogPosts.tsx";
import * as $$$$$$71 from "./sections/LightTerms.tsx";
import * as $$$$$$72 from "./sections/LogoCarousel.tsx";
import * as $$$$$$85 from "./sections/MainFeatures.tsx";
import * as $$$$$$73 from "./sections/MCPMeshBenefits.tsx";
import * as $$$$$$74 from "./sections/MCPMeshContextManagement.tsx";
import * as $$$$$$75 from "./sections/MCPMeshDecoCMS.tsx";
import * as $$$$$$76 from "./sections/MCPMeshDeployAnywhere.tsx";
import * as $$$$$$77 from "./sections/MCPMeshFeatures.tsx";
import * as $$$$$$78 from "./sections/MCPMeshHowItWorks.tsx";
import * as $$$$$$79 from "./sections/MCPMeshLayers.tsx";
import * as $$$$$$80 from "./sections/MCPMeshProblem.tsx";
import * as $$$$$$81 from "./sections/MCPMeshProblemRedShadow.tsx";
import * as $$$$$$82 from "./sections/MCPMeshProblemStatement.tsx";
import * as $$$$$$83 from "./sections/MCPMeshVideo.tsx";
import * as $$$$$$84 from "./sections/MCPMeshWhyUs.tsx";
import * as $$$$$$86 from "./sections/ModelsTable.tsx";
import * as $$$$$$87 from "./sections/OnePlatformTwoSurfaces.tsx";
import * as $$$$$$88 from "./sections/PartnerBenefits.tsx";
import * as $$$$$$89 from "./sections/PartnerDirectory.tsx";
import * as $$$$$$90 from "./sections/PartnerHighlights.tsx";
import * as $$$$$$92 from "./sections/PartnersFAQ.tsx";
import * as $$$$$$93 from "./sections/PartnersFinalCTA.tsx";
import * as $$$$$$94 from "./sections/PartnersHero.tsx";
import * as $$$$$$91 from "./sections/PartnerTiers.tsx";
import * as $$$$$$95 from "./sections/Podcasts.tsx";
import * as $$$$$$96 from "./sections/PricingPlans.tsx";
import * as $$$$$$97 from "./sections/PricingToggle.tsx";
import * as $$$$$$98 from "./sections/ProblemCards.tsx";
import * as $$$$$$99 from "./sections/ProblemStatement.tsx";
import * as $$$$$$100 from "./sections/ProductRoadmap.tsx";
import * as $$$$$$101 from "./sections/ProgramSteps.tsx";
import * as $$$$$$102 from "./sections/ProgramSteps4Col.tsx";
import * as $$$$$$103 from "./sections/ProjectGrid.tsx";
import * as $$$$$$104 from "./sections/RelatedBlogPosts.tsx";
import * as $$$$$$105 from "./sections/RoadmapFeatures.tsx";
import * as $$$$$$106 from "./sections/RoadmapPage.tsx";
import * as $$$$$$107 from "./sections/Sitemap.tsx";
import * as $$$$$$108 from "./sections/Statement.tsx";
import * as $$$$$$109 from "./sections/TextMedia.tsx";
import * as $$$$$$110 from "./sections/Theme/Theme.tsx";
import * as $$$$$$111 from "./sections/ThreeCards.tsx";
import * as $$$$$$112 from "./sections/WhoShouldApply.tsx";

const manifest = {
  "loaders": {
    "site/loaders/getRoadmapFeatures.ts": $$$0,
    "site/loaders/listFeatures.ts": $$$1,
    "site/loaders/posthogConfig.ts": $$$2,
    "site/loaders/sitemap.ts": $$$3,
  },
  "sections": {
    "site/sections/AgentTavano/Benefits.tsx": $$$$$$10,
    "site/sections/AgentTavano/Context.tsx": $$$$$$12,
    "site/sections/AgentTavano/CTA.tsx": $$$$$$11,
    "site/sections/AgentTavano/Features.tsx": $$$$$$13,
    "site/sections/AgentTavano/Hero.tsx": $$$$$$14,
    "site/sections/AgentTavano/Showcase.tsx": $$$$$$15,
    "site/sections/AIPartnerExclusivity.tsx": $$$$$$0,
    "site/sections/AIPartnerFinalCTA.tsx": $$$$$$1,
    "site/sections/AIPartnerFooter.tsx": $$$$$$2,
    "site/sections/AIPartnerHero.tsx": $$$$$$3,
    "site/sections/AIPartnerProcessSteps.tsx": $$$$$$4,
    "site/sections/AIPartnerProgramOverview.tsx": $$$$$$5,
    "site/sections/AIPartnerSocialProof.tsx": $$$$$$6,
    "site/sections/AIPartnerTheShift.tsx": $$$$$$7,
    "site/sections/AIPartnerValueProposition.tsx": $$$$$$8,
    "site/sections/AIPartnerWhoThisIsFor.tsx": $$$$$$9,
    "site/sections/Analytics/PostHog.tsx": $$$$$$16,
    "site/sections/ApplicationForm.tsx": $$$$$$17,
    "site/sections/ApplicationProcess.tsx": $$$$$$18,
    "site/sections/AutonomyControl.tsx": $$$$$$19,
    "site/sections/BackboneSection.tsx": $$$$$$20,
    "site/sections/BentoFeatures.tsx": $$$$$$21,
    "site/sections/BlackFridayCountdown.tsx": $$$$$$22,
    "site/sections/BlackFridayFeatures.tsx": $$$$$$23,
    "site/sections/BlackFridayHero.tsx": $$$$$$24,
    "site/sections/BlogCategories.tsx": $$$$$$25,
    "site/sections/BlogFilteredPosts.tsx": $$$$$$26,
    "site/sections/BlogPost.tsx": $$$$$$27,
    "site/sections/BlogPosts.tsx": $$$$$$28,
    "site/sections/BlogPostsCarousel.tsx": $$$$$$29,
    "site/sections/ChallengeHero.tsx": $$$$$$30,
    "site/sections/CommunicationOSFeatures.tsx": $$$$$$31,
    "site/sections/CommunicationOSHero.tsx": $$$$$$32,
    "site/sections/CommunicationOSJourney.tsx": $$$$$$33,
    "site/sections/CommunicationOSProblem.tsx": $$$$$$34,
    "site/sections/CommunicationOSSolution.tsx": $$$$$$35,
    "site/sections/ComparisonTable.tsx": $$$$$$36,
    "site/sections/ConnectionsGrid.tsx": $$$$$$37,
    "site/sections/CustomerLogos.tsx": $$$$$$38,
    "site/sections/DecoSitesHero.tsx": $$$$$$39,
    "site/sections/Document.tsx": $$$$$$40,
    "site/sections/EnterpriseComparison.tsx": $$$$$$41,
    "site/sections/EnterpriseGovernance.tsx": $$$$$$42,
    "site/sections/EnterpriseHero.tsx": $$$$$$43,
    "site/sections/EnterprisePainPoints.tsx": $$$$$$44,
    "site/sections/EnterpriseStandards.tsx": $$$$$$45,
    "site/sections/EnterpriseValueProp.tsx": $$$$$$46,
    "site/sections/ExplainerSection.tsx": $$$$$$47,
    "site/sections/FAQ.tsx": $$$$$$48,
    "site/sections/Features.tsx": $$$$$$49,
    "site/sections/FinalCTA.tsx": $$$$$$50,
    "site/sections/FinalCTACMS.tsx": $$$$$$51,
    "site/sections/FinalCTAMCPMesh.tsx": $$$$$$52,
    "site/sections/FinalCTASimple.tsx": $$$$$$53,
    "site/sections/FindPartnerHero.tsx": $$$$$$54,
    "site/sections/Footer.tsx": $$$$$$55,
    "site/sections/FormNewsletter.tsx": $$$$$$56,
    "site/sections/FoundationFeatures.tsx": $$$$$$57,
    "site/sections/GoogleAbout.tsx": $$$$$$58,
    "site/sections/HackathonHero.tsx": $$$$$$59,
    "site/sections/Header.tsx": $$$$$$60,
    "site/sections/Hero.tsx": $$$$$$61,
    "site/sections/HeroAIPlatform.tsx": $$$$$$62,
    "site/sections/HeroCMS.tsx": $$$$$$63,
    "site/sections/HeroInteractive.tsx": $$$$$$64,
    "site/sections/HeroMCPMesh.tsx": $$$$$$65,
    "site/sections/HeroSection.tsx": $$$$$$66,
    "site/sections/HeroSecureEndpoint.tsx": $$$$$$67,
    "site/sections/ImageShowcase.tsx": $$$$$$68,
    "site/sections/ItWorks.tsx": $$$$$$69,
    "site/sections/LatestBlogPosts.tsx": $$$$$$70,
    "site/sections/LightTerms.tsx": $$$$$$71,
    "site/sections/LogoCarousel.tsx": $$$$$$72,
    "site/sections/MainFeatures.tsx": $$$$$$85,
    "site/sections/MCPMeshBenefits.tsx": $$$$$$73,
    "site/sections/MCPMeshContextManagement.tsx": $$$$$$74,
    "site/sections/MCPMeshDecoCMS.tsx": $$$$$$75,
    "site/sections/MCPMeshDeployAnywhere.tsx": $$$$$$76,
    "site/sections/MCPMeshFeatures.tsx": $$$$$$77,
    "site/sections/MCPMeshHowItWorks.tsx": $$$$$$78,
    "site/sections/MCPMeshLayers.tsx": $$$$$$79,
    "site/sections/MCPMeshProblem.tsx": $$$$$$80,
    "site/sections/MCPMeshProblemRedShadow.tsx": $$$$$$81,
    "site/sections/MCPMeshProblemStatement.tsx": $$$$$$82,
    "site/sections/MCPMeshVideo.tsx": $$$$$$83,
    "site/sections/MCPMeshWhyUs.tsx": $$$$$$84,
    "site/sections/ModelsTable.tsx": $$$$$$86,
    "site/sections/OnePlatformTwoSurfaces.tsx": $$$$$$87,
    "site/sections/PartnerBenefits.tsx": $$$$$$88,
    "site/sections/PartnerDirectory.tsx": $$$$$$89,
    "site/sections/PartnerHighlights.tsx": $$$$$$90,
    "site/sections/PartnersFAQ.tsx": $$$$$$92,
    "site/sections/PartnersFinalCTA.tsx": $$$$$$93,
    "site/sections/PartnersHero.tsx": $$$$$$94,
    "site/sections/PartnerTiers.tsx": $$$$$$91,
    "site/sections/Podcasts.tsx": $$$$$$95,
    "site/sections/PricingPlans.tsx": $$$$$$96,
    "site/sections/PricingToggle.tsx": $$$$$$97,
    "site/sections/ProblemCards.tsx": $$$$$$98,
    "site/sections/ProblemStatement.tsx": $$$$$$99,
    "site/sections/ProductRoadmap.tsx": $$$$$$100,
    "site/sections/ProgramSteps.tsx": $$$$$$101,
    "site/sections/ProgramSteps4Col.tsx": $$$$$$102,
    "site/sections/ProjectGrid.tsx": $$$$$$103,
    "site/sections/RelatedBlogPosts.tsx": $$$$$$104,
    "site/sections/RoadmapFeatures.tsx": $$$$$$105,
    "site/sections/RoadmapPage.tsx": $$$$$$106,
    "site/sections/Sitemap.tsx": $$$$$$107,
    "site/sections/Statement.tsx": $$$$$$108,
    "site/sections/TextMedia.tsx": $$$$$$109,
    "site/sections/Theme/Theme.tsx": $$$$$$110,
    "site/sections/ThreeCards.tsx": $$$$$$111,
    "site/sections/WhoShouldApply.tsx": $$$$$$112,
  },
  "actions": {
    "site/actions/airtable/createRecord.ts": $$$$$$$$$0,
    "site/actions/resend/createContact.ts": $$$$$$$$$1,
    "site/actions/submitFeatureSuggestion.ts": $$$$$$$$$2,
    "site/actions/upvoteFeature.ts": $$$$$$$$$3,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/nuvemshop.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
