import type { AppContext } from "../apps/site.ts";

// Airtable configuration for Feature Requests
// Base ID and Table Name are safe to hardcode, token comes from env/context
const AIRTABLE_CONFIG = {
  baseId: "app315UvoWO5vZcJh",
  tableName: "Requests",
};

interface Props {
  title: string;
  description: string;
  email?: string;
}

interface SubmitResponse {
  success: boolean;
  featureId?: string;
  error?: string;
}

/**
 * @title Submit Feature Suggestion
 * @description Create a new feature suggestion in the Airtable roadmap
 */
export default async function submitFeatureSuggestion(
  { title, description, email }: Props,
  _req: Request,
  ctx: AppContext
): Promise<SubmitResponse> {
  try {
    console.log(`💡 [ACTION] Submitting feature to Airtable: ${title}`);
    
    const { baseId, tableName } = AIRTABLE_CONFIG;
    
    // Get API token from context (configured in Admin)
    let apiToken: string | undefined;
    if (typeof ctx.airtableApiKey === 'string') {
      apiToken = ctx.airtableApiKey;
    } else {
      apiToken = await ctx.airtableApiKey?.get?.();
    }
    
    if (!apiToken) {
      console.error('❌ [ACTION] Missing Airtable API Key');
      return {
        success: false,
        error: 'Airtable API Key not configured. Please set it in the Admin panel.',
      };
    }
    
    console.log('🔍 [ACTION] Using Airtable config:', { baseId, tableName, hasToken: !!apiToken });
    
    // Build the fields object - only include editable fields
    // Note: "Created" is auto-generated by Airtable, don't set it manually
    const fields: Record<string, string> = {
      'Title': title,
      'Description': description,
    };
    
    // Only add Email if provided
    if (email && email.trim()) {
      fields['Email'] = email.trim();
    }
    
    console.log('📝 [ACTION] Sending fields:', fields);
    
    // Create record in Airtable
    const response = await fetch(
      `https://api.airtable.com/v0/${baseId}/${encodeURIComponent(tableName)}`,
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${apiToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ fields })
      }
    );
    
    if (!response.ok) {
      let errorMessage = '';
      const contentType = response.headers.get('content-type');
      
      try {
        if (contentType?.includes('application/json')) {
          const errorJson = await response.json();
          errorMessage = errorJson.error?.message || errorJson.error?.type || JSON.stringify(errorJson);
        } else {
          errorMessage = await response.text();
        }
      } catch {
        errorMessage = response.statusText;
      }
      
      console.error(`❌ [ACTION] Airtable API error:`, {
        status: response.status,
        message: errorMessage,
        sentFields: fields
      });
      
      return { 
        success: false, 
        error: `Airtable error (${response.status}): ${errorMessage}` 
      };
    }
    
    const result = await response.json();
    console.log(`✅ [ACTION] Feature created in Airtable:`, result.id);
    
    return {
      success: true,
      featureId: result.id
    };
  } catch (error) {
    console.error(`❌ [ACTION] Error submitting feature:`, error);
    
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
